In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [4]:
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [6]:
 X = df.drop('HeartDisease',axis='columns')

In [7]:
y=df.HeartDisease

In [12]:
dummies = pd.get_dummies(X,drop_first=True)

In [13]:
df = pd.concat([df,dummies], axis='columns')

In [14]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,...,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,M,ATA,140,289,0,Normal,172,N,0.0,...,0.0,1,1,0,0,1,0,0,0,1
1,49,F,NAP,160,180,0,Normal,156,N,1.0,...,1.0,0,0,1,0,1,0,0,1,0
2,37,M,ATA,130,283,0,ST,98,N,0.0,...,0.0,1,1,0,0,0,1,0,0,1
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,...,1.5,0,0,0,0,1,0,1,1,0
4,54,M,NAP,150,195,0,Normal,122,N,0.0,...,0.0,1,0,1,0,1,0,0,0,1

In [16]:
X=df.drop(['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'],axis='columns')

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:3]

array([[-1.4331398 ,  0.41090889,  0.82507026, -0.55134134,  1.38292822,
        -0.83243239, -1.11311472, -1.4331398 ,  0.41090889,  0.82507026,
        -0.55134134,  1.38292822, -0.83243239, -0.51595242,  0.51595242,
        -1.08413811,  2.07517671, -0.53283777, -0.22967867, -0.50747832,
         0.81427482, -0.49044933,  0.8235563 , -0.8235563 , -0.27144836,
        -1.00218103,  1.15067399, -1.4331398 ,  0.41090889,  0.82507026,
        -0.55134134,  1.38292822, -0.83243239,  0.51595242,  2.07517671,
        -0.53283777, -0.22967867,  0.81427482, -0.49044933, -0.8235563 ,
        -1.00218103,  1.15067399],
       [-0.47848359,  1.49175234, -0.17196105, -0.55134134,  0.75415714,
         0.10566353,  0.89837999, -0.47848359,  1.49175234, -0.17196105,
        -0.55134134,  0.75415714,  0.10566353,  1.93816322, -1.93816322,
        -1.08413811, -0.48188667,  1.87674385, -0.22967867, -0.50747832,
         0.81427482, -0.49044933,  0.8235563 , -0.8235563 , -0.27144836,
         0.99782372, -0.86905588, -0.47848359,  1.49175234, -0.17196105,
        -0.55134134,  0.75415714,  0.10566353, -1.93816322, -0.48188667,
         1.87674385, -0.22967867,  0.81427482, -0.49044933, -0.8235563 ,
         0.99782372, -0.86905588],
       [-1.75135854, -0.12951283,  0.7701878 , -0.55134134, -1.52513802,
        -0.83243239, -1.11311472, -1.75135854, -0.12951283,  0.7701878 ,
        -0.55134134, -1.52513802, -0.83243239, -0.51595242,  0.51595242,
        -1.08413811,  2.07517671, -0.53283777, -0.22967867, -0.50747832,
        -1.22808661,  2.03894663,  0.8235563 , -0.8235563 , -0.27144836,
        -1.00218103,  1.15067399, -1.75135854, -0.12951283,  0.7701878 ,
        -0.55134134, -1.52513802, -0.83243239,  0.51595242,  2.07517671,
        -0.53283777, -0.22967867, -1.22808661,  2.03894663, -0.8235563 ,
        -1.00218103,  1.15067399]])

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, stratify=y, random_state=10)

In [22]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

scores = cross_val_score(SVC(C=10), X_train, y_train, cv=5)
scores

array([1.        , 1.        , 1.        , 0.98540146, 1.        ])

In [24]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, y_train)
bag_model.oob_score_

1.0